### ISSUE TITLE
Feature request: Font size parameter in .yaml

### ISSUE THREAD

**Issue by aldostools** [TheRouletteBoi/RouLetteVshMenu#24]
As title says.. Let change the overlay font size. Make it show smaller or bigger.

**Comment by TheRouletteBoi** [comment]
Updated the YAML to support font size
https://gofile.io/d/mNYdu9


```yaml
version: 2
overlay:
   displayMode: XMB_GAME # Available options XMB_GAME, XMB, GAME 
   position: TOP_LEFT # Available options TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT
   showFPS: On
   showCpuInfo: On
   showGpuInfo: On
   showRamInfo: Off
   showFanSpeed: On
   showFirmware: On
   showAppName: On
   showClockSpeeds: On
   temperatureType: BOTH # Available options BOTH, CELSIUS, FAHRENHEIT 
   textSize: 20.0
   
```
